create_guest:
  fields:
    device_id:
      required: true
      selector:
        text:
    ttl_hours:
      required: false
      default: 24
      selector:
        number:
          min: 1
          max: 720
          unit_of_measurement: h
    admin:
      required: false
      default: false
      selector:
        boolean:

remove_guest:
  fields:
    device_id:
      required: true
      selector:
        text:
    user_id:
      required: true
      selector:
        text:
